### ISSUE TITLE
cannot start the container

### ISSUE THREAD

**Issue by karkinious** [KyrosWeb/PSPhree_Public#2]
im trying to set up via portainer but it exits immediately 
logs show "exec /usr/local/bin/httpd-foreground: exec format error"

**Comment by KyrosWeb** [comment]
Hi it is architecture problem, where are you trying to start it? Can you provide me the CPU ?

**Comment by karkinious** [comment]
its not running on proxmox server Intel nuc actually it's nested docker on lxc container

**Comment by KyrosWeb** [comment]
Could you delete the docker container image , reclone the repo and try to start it now? Thanks

**Comment by karkinious** [comment]
pulled latest image everything now loads i will test if jailbreak in ps4 works as well

**Comment by KyrosWeb** [comment]
Let me know !

**Comment by karkinious** [comment]
Jailbreak works perfectly thank you so much for your prompt response
